import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <Link href="/">Home</Link>
            <Link href="/travel-booking">Travel Booking</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
